
from menu import menu_prompt

def main():
    menu_prompt()

main()

#AFTER SELECTING ANY OPTION PLEASE SCROLL UP THE TERMINAL TO SEE THE OUTPUT 
#SINCE THE MENU WILL BE PRESENTED ONCE AGAIN TO CONTINUE USING MORE OPTIONS

#FILES MAIN.PY , MENU.PY, ACTIONS.PY , DATA.PY AND STUDENT.CSV MUST BE ON THE SAME DIRECTORY