import random

random_number= random.randint(1, 10)
user_number= 0


print (f"Random number generated by system is {random_number} ")

while (user_number != random_number ):
    user_number= int(input("Please enter a number from 1 to 10: "))

print("Congratulations!! ,  you have guessed the random number")